//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResouce {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResouce.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string ButtonCreateCategory {
            get {
                return ResourceManager.GetString("ButtonCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự .
        /// </summary>
        public static string Category_DisplayOrder {
            get {
                return ResourceManager.GetString("Category_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả SEO.
        /// </summary>
        public static string Category_MetaDecriptions {
            get {
                return ResourceManager.GetString("Category_MetaDecriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string Category_Metakeywords {
            get {
                return ResourceManager.GetString("Category_Metakeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Category_Metatitle {
            get {
                return ResourceManager.GetString("Category_Metatitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục Cha.
        /// </summary>
        public static string Category_ParenID {
            get {
                return ResourceManager.GetString("Category_ParenID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập điền tên danh mục..
        /// </summary>
        public static string Category_RequiredName {
            get {
                return ResourceManager.GetString("Category_RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn trạng thái.
        /// </summary>
        public static string Category_RequiredStatus {
            get {
                return ResourceManager.GetString("Category_RequiredStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiêu đề Seo.
        /// </summary>
        public static string Category_SeoTitle {
            get {
                return ResourceManager.GetString("Category_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string Category_ShowOnHome {
            get {
                return ResourceManager.GetString("Category_ShowOnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Category_Status {
            get {
                return ResourceManager.GetString("Category_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string CategoryButtonDelete {
            get {
                return ResourceManager.GetString("CategoryButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string CategoryButtonUpdate {
            get {
                return ResourceManager.GetString("CategoryButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới danh mục.
        /// </summary>
        public static string CategoryCreate {
            get {
                return ResourceManager.GetString("CategoryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công..
        /// </summary>
        public static string InsertCategoryFail {
            get {
                return ResourceManager.GetString("InsertCategoryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ Thống.
        /// </summary>
        public static string Left_Menu_System {
            get {
                return ResourceManager.GetString("Left_Menu_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Letft_Menu_Catefory {
            get {
                return ResourceManager.GetString("Letft_Menu_Catefory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng lý chung.
        /// </summary>
        public static string Letft_Menu_general_managerment {
            get {
                return ResourceManager.GetString("Letft_Menu_general_managerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string Letft_Menu_Home {
            get {
                return ResourceManager.GetString("Letft_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB Người dùng.
        /// </summary>
        public static string Letft_Menu_logo {
            get {
                return ResourceManager.GetString("Letft_Menu_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string Letft_Menu_News {
            get {
                return ResourceManager.GetString("Letft_Menu_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Letft_Menu_Product {
            get {
                return ResourceManager.GetString("Letft_Menu_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa không thành công..
        /// </summary>
        public static string UpdateCategoryFail {
            get {
                return ResourceManager.GetString("UpdateCategoryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Viêt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
